#
#   ____                     __ _ _
#  | __ ) _ __ _____      __/ _(_) | ___
#  |  _ \| '__/ _ \ \ /\ / / |_| | |/ _ \
#  | |_) | | |  __/\ V  V /|  _| | |  __/
#  |____/|_|  \___| \_/\_/ |_| |_|_|\___|
#

# Reference: https://github.com/Homebrew/homebrew-bundle
# https://github.com/Homebrew

cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/science'

# brew install <package>
brew 'git'
brew 'tree'
brew 'tmux'
brew 'ccat'
brew 'icdiff'
brew 'diff-so-fancy'
brew 'pyenv-virtualenv'
brew 'rbenv'

# http://brew.sh/homebrew-science/
tap 'caskroom/cask'

# https://caskroom.github.io/
cask 'spotify'
cask 'hyper'
cask 'alfred'
cask 'firefox'
