#!/bin/bash

# (Cds)
alias tmp="cd /tmp"
alias dot="cd $DOT_HOME"
alias dev="cd $DEV_HOME"
alias work="cd $DEV_HOME/work"
alias code="cd $DEV_HOME/code"
alias fork="cd $DEV_HOME/fork"

# (Git)
alias g="git"
alias g-="git checkout -"

# (Editing)
alias vi="vim"
alias e="mvim"
alias ealias="vi $DOT_HOME/shell/aliases"
alias epath="vi $DOT_HOME/shell/paths"
alias eexports="vi $DOT_HOME/shell/exports"
alias ework="vi $DOT_HOME/shell/work"
alias ezshrc="vi ~/.zshrc"
alias eomz="vi ~/.oh-my-zsh"

# (Cli)
alias cat="ccat"
alias cra="create-react-app"
alias rn="react-native"
alias ss="source ~/.zshrc"
alias h="history"
alias f="open -a Finder"
alias k="kill -9"
alias cap="capture_screen"

# (Elm)
alias elmr="elm-repl"
alias elmm="elm-make"
alias epm="elm-package"

# (Ruby)
alias be="bundle exec"
alias bi="bundle install"
