#!/bin/bash

# (System)
export SHELL=/usr/local/bin/zsh
export LANG=en_US.UTF-8

# (Homes)
export DEV_HOME=$HOME/dev
export WORK_HOME=$DEV_HOME/work
export DOT_HOME=$HOME/.dotfiles
export ANDROID_HOME=$HOME/Library/Android/sdk
export RVM_HOME=$HOME/.rvm
export CARGO_HOME=$HOME/.cargo

# - py
export PIP_INSTALL_HOME=/usr/local/lib/python2.7/site-packages
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$DEV_HOME/venv

if [ "$IS_LINUX" -eq 1 ]; then
	export BREW_HOME=/home/linuxbrew/.linuxbrew
	export MANPATH=$BREW_HOME/share/man:$MANPATH
	export INFOPATH=$BREW_HOME/share/info:$INFOPATH
elif [ "$IS_MAC" -eq 1 ]; then
	export CATALINA_HOME=/Library/Tomcat
	export MYSQL_HOME=/usr/local/mysql
	export JAVA_HOME=$(/usr/libexec/java_home)
fi
