#!/bin/bash

# Oh-my-zsh (zsh plugin manager: https://github.com/robbyrussell/oh-my-zsh)

# (general)
export ZSH=$HOME/.oh-my-zsh
export UPDATE_ZSH_DAYS=15
export MANPATH="/usr/local/man:$MANPATH"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="mm/dd/yyyy"

# (theme)
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_CUSTOM=$DOT_HOME/shell/custom
ZSH_THEME=""

# (plugins)
# Plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
