#!/bin/bash

cd "$(dirname $0)/.."

. script/utils

DOTFILES_ROOT=$(pwd -P)
DOTFILES=(
  tmux/tmux.conf
  vim/vimrc
  shell/zshrc
  git/gitconfig
  git/gitignore
  git/gitconfig.local
  formatter/prettierrc.js
  formatter/editorconfig
  brew/Brewfile
) # Relative path to root dir

go() {
  set -e

  echo ''
  info 'machine is under bootstrap 🚀'
  echo ''

  . script/setup_gitconfig
  . script/install_dotfiles
  . script/install_homebrew

  echo ''
  success ' git configured ✔,  dotfiles installed ✔ , homebrew installed ✔ . ✨✨✨'
}

go "$@"
