#!/bin/bash

install_homebrew() {
    if test ! $(which brew)
    then
        info "installing Homebrew"
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        success "Homebrew installed"
    fi
}

install_homebrew "$@"
